export const allServices = [
  { title: "Парихмахерские услуги", imageUrl: "/images/services/1.jpg" },
  { title: "Ногтевой сервис", imageUrl: "./images/services/2.jpg" },
  { title: "Косметология", imageUrl: "./images/services/3.jpg" },
  { title: "Окрашивание волос", imageUrl: "./images/services/4.jpg" },
  { title: "Шугаринг / Восковая эпиляция", imageUrl: "./images/services/5.jpg" },
  { title: "Визаж", imageUrl: "./images/services/6.jpg" },
  { title: "Массаж / Все виды массажа", imageUrl: "./images/services/7.jpg" },
  { title: "Наращивание волос", imageUrl: "./images/services/8.jpg" },
  { title: "Наращивание ресниц", imageUrl: "./images/services/9.jpg" },
  { title: "Фотографии / Фотограф", imageUrl: "./images/services/10.jpg" },
  { title: "Мастер бровист", imageUrl: "./images/services/11.jpg" },
  { title: "Перманентный макияж", imageUrl: "./images/services/12.jpg" },
  { title: "Тату-мастер", imageUrl: "./images/services/13.jpg" },
  { title: "Фитнес / Тренера", imageUrl: "./images/services/14.jpg" },
  { title: "Йога-мастер", imageUrl: "./images/services/15.jpg" },
  { title: "Электроэпиляция", imageUrl: "./images/services/16.jpg" },
  { title: "Мануальная терапия", imageUrl: "./images/services/17.jpg" },
  { title: "Психология", imageUrl: "./images/services/18.jpg" },
  { title: "Похудение / Диетология", imageUrl: "./images/services/19.jpg" },
  { title: "Обучение для мастеров", imageUrl: "./images/services/20.jpg" },
  { title: "Преподаватели / репетиторы", imageUrl: "./images/services/21.jpg" },
];

export const allStates = [
  { abbreviation: "AL", english: "Alabama", russian: "Алабама" },
  { abbreviation: "AK", english: "Alaska", russian: "Аляска" },
  { abbreviation: "AZ", english: "Arizona", russian: "Аризона" },
  { abbreviation: "AR", english: "Arkansas", russian: "Арканзас" },
  { abbreviation: "CA", english: "California", russian: "Калифорния" },
  { abbreviation: "CO", english: "Colorado", russian: "Колорадо" },
  { abbreviation: "CT", english: "Connecticut", russian: "Коннектикут" },
  { abbreviation: "DE", english: "Delaware", russian: "Делавер" },
  { abbreviation: "DC", english: "District of Columbia", russian: "Округ Колумбия" },
  { abbreviation: "FL", english: "Florida", russian: "Флорида" },
  { abbreviation: "GA", english: "Georgia", russian: "Джорджия" },
  { abbreviation: "HI", english: "Hawaii", russian: "Гавайи" },
  { abbreviation: "ID", english: "Idaho", russian: "Айдахо" },
  { abbreviation: "IL", english: "Illinois", russian: "Иллинойс" },
  { abbreviation: "IN", english: "Indiana", russian: "Индиана" },
  { abbreviation: "IA", english: "Iowa", russian: "Айова" },
  { abbreviation: "KS", english: "Kansas", russian: "Канзас" },
  { abbreviation: "KY", english: "Kentucky", russian: "Кентукки" },
  { abbreviation: "LA", english: "Louisiana", russian: "Луизиана" },
  { abbreviation: "ME", english: "Maine", russian: "Мэн" },
  { abbreviation: "MD", english: "Maryland", russian: "Мэриленд" },
  { abbreviation: "MA", english: "Massachusetts", russian: "Массачусетс" },
  { abbreviation: "MI", english: "Michigan", russian: "Мичиган" },
  { abbreviation: "MN", english: "Minnesota", russian: "Миннесота" },
  { abbreviation: "MS", english: "Mississippi", russian: "Миссисипи" },
  { abbreviation: "MO", english: "Missouri", russian: "Миссури" },
  { abbreviation: "MT", english: "Montana", russian: "Монтана" },
  { abbreviation: "NE", english: "Nebraska", russian: "Небраска" },
  { abbreviation: "NV", english: "Nevada", russian: "Невада" },
  { abbreviation: "NH", english: "New Hampshire", russian: "Нью-Гэмпшир" },
  { abbreviation: "NJ", english: "New Jersey", russian: "Нью-Джерси" },
  { abbreviation: "NM", english: "New Mexico", russian: "Нью-Мексико" },
  { abbreviation: "NY", english: "New York", russian: "Нью-Йорк" },
  { abbreviation: "NC", english: "North Carolina", russian: "Северная Каролина" },
  { abbreviation: "ND", english: "North Dakota", russian: "Северная Дакота" },
  { abbreviation: "OH", english: "Ohio", russian: "Огайо" },
  { abbreviation: "OK", english: "Oklahoma", russian: "Оклахома" },
  { abbreviation: "OR", english: "Oregon", russian: "Орегон" },
  { abbreviation: "PA", english: "Pennsylvania", russian: "Пенсильвания" },
  { abbreviation: "RI", english: "Rhode Island", russian: "Род-Айленд" },
  { abbreviation: "SC", english: "South Carolina", russian: "Южная Каролина" },
  { abbreviation: "SD", english: "South Dakota", russian: "Южная Дакота" },
  { abbreviation: "TN", english: "Tennessee", russian: "Теннеси" },
  { abbreviation: "TX", english: "Texas", russian: "Техас" },
  { abbreviation: "UT", english: "Utah", russian: "Юта" },
  { abbreviation: "VT", english: "Vermont", russian: "Вермонт" },
  { abbreviation: "VA", english: "Virginia", russian: "Вирджиния" },
  { abbreviation: "WA", english: "Washington", russian: "Вашингтон" },
  { abbreviation: "WV", english: "West Virginia", russian: "Западная Вирджиния" },
  { abbreviation: "WI", english: "Wisconsin", russian: "Висконсин" },
  { abbreviation: "WY", english: "Wyoming", russian: "Вайоминг" },
];

export const allCities = [
  // Alabama
  { state: "AL", english: "Birmingham", russian: "Бирмингем" },
  { state: "AL", english: "Montgomery", russian: "Монтгомери" },
  { state: "AL", english: "Mobile", russian: "Мобил" },
  { state: "AL", english: "Huntsville", russian: "Хантсвилл" },
  { state: "AL", english: "Tuscaloosa", russian: "Таскалуса" },
  { state: "AL", english: "Hoover", russian: "Хувер" },
  { state: "AL", english: "Dothan", russian: "Дотан" },
  { state: "AL", english: "Auburn", russian: "Оберн" },
  { state: "AL", english: "Decatur", russian: "Декейтер" },
  { state: "AL", english: "Madison", russian: "Мэдисон" },

  // Alaska
  { state: "AK", english: "Anchorage", russian: "Анкоридж" },
  { state: "AK", english: "Juneau", russian: "Джуно" },
  { state: "AK", english: "Fairbanks", russian: "Фэрбенкс" },
  { state: "AK", english: "Wasilla", russian: "Василла" },
  { state: "AK", english: "Sitka", russian: "Ситка" },
  { state: "AK", english: "Ketchikan", russian: "Кетчикан" },
  { state: "AK", english: "Kenai", russian: "Кенай" },
  { state: "AK", english: "Kodiak", russian: "Кадьяк" },
  { state: "AK", english: "Bethel", russian: "Бетел" },
  { state: "AK", english: "Palmer", russian: "Палмер" },

  // Arizona
  { state: "AZ", english: "Phoenix", russian: "Финикс" },
  { state: "AZ", english: "Tucson", russian: "Тусон" },
  { state: "AZ", english: "Mesa", russian: "Меса" },
  { state: "AZ", english: "Chandler", russian: "Чандлер" },
  { state: "AZ", english: "Scottsdale", russian: "Скоттсдейл" },
  { state: "AZ", english: "Gilbert", russian: "Гилберт" },
  { state: "AZ", english: "Glendale", russian: "Глендейл" },
  { state: "AZ", english: "Tempe", russian: "Темпе" },
  { state: "AZ", english: "Peoria", russian: "Пеория" },
  { state: "AZ", english: "Surprise", russian: "Сюрприз" },

  // Arkansas
  { state: "AR", english: "Little Rock", russian: "Литл-Рок" },
  { state: "AR", english: "Fort Smith", russian: "Форт-Смит" },
  { state: "AR", english: "Fayetteville", russian: "Фейетвилл" },
  { state: "AR", english: "Springdale", russian: "Спрингдейл" },
  { state: "AR", english: "Jonesboro", russian: "Джонсборо" },
  { state: "AR", english: "North Little Rock", russian: "Норт-Литл-Рок" },
  { state: "AR", english: "Conway", russian: "Конвей" },
  { state: "AR", english: "Rogers", russian: "Роджерс" },
  { state: "AR", english: "Pine Bluff", russian: "Пайн-Блафф" },
  { state: "AR", english: "Bentonville", russian: "Бентонвилл" },

  // California
  { state: "CA", english: "Los Angeles", russian: "Лос-Анджелес" },
  { state: "CA", english: "San Diego", russian: "Сан-Диего" },
  { state: "CA", english: "San Jose", russian: "Сан-Хосе" },
  { state: "CA", english: "San Francisco", russian: "Сан-Франциско" },
  { state: "CA", english: "Fresno", russian: "Фресно" },
  { state: "CA", english: "Sacramento", russian: "Сакраменто" },
  { state: "CA", english: "Long Beach", russian: "Лонг-Бич" },
  { state: "CA", english: "Oakland", russian: "Окленд" },
  { state: "CA", english: "Bakersfield", russian: "Бейкерсфилд" },
  { state: "CA", english: "Anaheim", russian: "Анахайм" },

  // Colorado
  { state: "CO", english: "Denver", russian: "Денвер" },
  { state: "CO", english: "Colorado Springs", russian: "Колорадо-Спрингс" },
  { state: "CO", english: "Aurora", russian: "Аврора" },
  { state: "CO", english: "Fort Collins", russian: "Форт-Коллинз" },
  { state: "CO", english: "Lakewood", russian: "Лейквуд" },
  { state: "CO", english: "Thornton", russian: "Торнтон" },
  { state: "CO", english: "Arvada", russian: "Арвада" },
  { state: "CO", english: "Westminster", russian: "Вестминстер" },
  { state: "CO", english: "Pueblo", russian: "Пуэбло" },
  { state: "CO", english: "Centennial", russian: "Сентенниал" },

  // Connecticut
  { state: "CT", english: "Bridgeport", russian: "Бриджпорт" },
  { state: "CT", english: "New Haven", russian: "Нью-Хейвен" },
  { state: "CT", english: "Hartford", russian: "Хартфорд" },
  { state: "CT", english: "Stamford", russian: "Стэмфорд" },
  { state: "CT", english: "Waterbury", russian: "Уотербери" },
  { state: "CT", english: "Norwalk", russian: "Норуолк" },
  { state: "CT", english: "Danbury", russian: "Данбери" },
  { state: "CT", english: "New Britain", russian: "Нью-Бритен" },
  { state: "CT", english: "West Hartford", russian: "Уэст-Хартфорд" },
  { state: "CT", english: "Greenwich", russian: "Гринвич" },

  // Delaware
  { state: "DE", english: "Wilmington", russian: "Уилмингтон" },
  { state: "DE", english: "Dover", russian: "Довер" },
  { state: "DE", english: "Newark", russian: "Ньюарк" },
  { state: "DE", english: "Middletown", russian: "Миддлтаун" },
  { state: "DE", english: "Smyrna", russian: "Смирна" },
  { state: "DE", english: "Milford", russian: "Милфорд" },
  { state: "DE", english: "Seaford", russian: "Сифорд" },
  { state: "DE", english: "Georgetown", russian: "Джорджтаун" },
  { state: "DE", english: "Elsmere", russian: "Элсмир" },
  { state: "DE", english: "New Castle", russian: "Нью-Касл" },

  // District of Columbia
  { state: "DC", english: "Washington", russian: "Вашингтон" },

  // Florida
  { state: "FL", english: "Jacksonville", russian: "Джексонвилл" },
  { state: "FL", english: "Miami", russian: "Майами" },
  { state: "FL", english: "Tampa", russian: "Тампа" },
  { state: "FL", english: "Orlando", russian: "Орландо" },
  { state: "FL", english: "St. Petersburg", russian: "Сент-Питерсберг" },
  { state: "FL", english: "Hialeah", russian: "Хайалиа" },
  { state: "FL", english: "Tallahassee", russian: "Таллахасси" },
  { state: "FL", english: "Fort Lauderdale", russian: "Форт-Лодердейл" },
  { state: "FL", english: "Port St. Lucie", russian: "Порт-Сент-Луси" },
  { state: "FL", english: "Cape Coral", russian: "Кейп-Корал" },

  // Georgia
  { state: "GA", english: "Atlanta", russian: "Атланта" },
  { state: "GA", english: "Augusta", russian: "Огаста" },
  { state: "GA", english: "Columbus", russian: "Колумбус" },
  { state: "GA", english: "Savannah", russian: "Саванна" },
  { state: "GA", english: "Athens", russian: "Афинс" },
  { state: "GA", english: "Sandy Springs", russian: "Сэнди-Спрингс" },
  { state: "GA", english: "Roswell", russian: "Розуэлл" },
  { state: "GA", english: "Macon", russian: "Мейкон" },
  { state: "GA", english: "Johns Creek", russian: "Джонс-Крик" },
  { state: "GA", english: "Albany", russian: "Олбани" },

  // Hawaii
  { state: "HI", english: "Honolulu", russian: "Гонолулу" },
  { state: "HI", english: "Hilo", russian: "Хило" },
  { state: "HI", english: "Kailua", russian: "Кайлуа" },
  { state: "HI", english: "Kapolei", russian: "Каполеи" },
  { state: "HI", english: "Kaneohe", russian: "Канеохе" },
  { state: "HI", english: "Mililani", russian: "Милилани" },
  { state: "HI", english: "Ewa Beach", russian: "Эва-Бич" },
  { state: "HI", english: "Kihei", russian: "Кихеи" },
  { state: "HI", english: "Waipahu", russian: "Вайпаху" },
  { state: "HI", english: "Pearl City", russian: "Перл-Сити" },

  // Idaho
  { state: "ID", english: "Boise", russian: "Бойсе" },
  { state: "ID", english: "Meridian", russian: "Меридиан" },
  { state: "ID", english: "Nampa", russian: "Нампа" },
  { state: "ID", english: "Idaho Falls", russian: "Айдахо-Фолс" },
  { state: "ID", english: "Pocatello", russian: "Покателло" },
  { state: "ID", english: "Caldwell", russian: "Колдуэлл" },
  { state: "ID", english: "Coeur d'Alene", russian: "Кур-д’Ален" },
  { state: "ID", english: "Twin Falls", russian: "Туин-Фолс" },
  { state: "ID", english: "Lewiston", russian: "Льюистон" },
  { state: "ID", english: "Post Falls", russian: "Пост-Фолс" },

  // Illinois
  { state: "IL", english: "Chicago", russian: "Чикаго" },
  { state: "IL", english: "Aurora", russian: "Аврора" },
  { state: "IL", english: "Naperville", russian: "Нейпервилл" },
  { state: "IL", english: "Joliet", russian: "Джолиет" },
  { state: "IL", english: "Rockford", russian: "Рокфорд" },
  { state: "IL", english: "Springfield", russian: "Спрингфилд" },
  { state: "IL", english: "Peoria", russian: "Пеория" },
  { state: "IL", english: "Elgin", russian: "Элджин" },
  { state: "IL", english: "Waukegan", russian: "Уокиган" },
  { state: "IL", english: "Cicero", russian: "Цицерон" },

  // Indiana
  { state: "IN", english: "Indianapolis", russian: "Индианаполис" },
  { state: "IN", english: "Fort Wayne", russian: "Форт-Уэйн" },
  { state: "IN", english: "Evansville", russian: "Эвансвилл" },
  { state: "IN", english: "South Bend", russian: "Саут-Бенд" },
  { state: "IN", english: "Carmel", russian: "Кармел" },
  { state: "IN", english: "Fishers", russian: "Фишерс" },
  { state: "IN", english: "Bloomington", russian: "Блумингтон" },
  { state: "IN", english: "Hammond", russian: "Хаммонд" },
  { state: "IN", english: "Gary", russian: "Гэри" },
  { state: "IN", english: "Lafayette", russian: "Лафайет" },

  // Iowa
  { state: "IA", english: "Des Moines", russian: "Де-Мойн" },
  { state: "IA", english: "Cedar Rapids", russian: "Сидар-Рапидс" },
  { state: "IA", english: "Davenport", russian: "Дэвенпорт" },
  { state: "IA", english: "Sioux City", russian: "Су-Сити" },
  { state: "IA", english: "Waterloo", russian: "Уотерлу" },
  { state: "IA", english: "Iowa City", russian: "Айова-Сити" },
  { state: "IA", english: "Council Bluffs", russian: "Каунсил-Блафс" },
  { state: "IA", english: "Ames", russian: "Эймс" },
  { state: "IA", english: "West Des Moines", russian: "Уэст-Де-Мойн" },
  { state: "IA", english: "Ankeny", russian: "Анкени" },

  // Kansas
  { state: "KS", english: "Wichita", russian: "Уичито" },
  { state: "KS", english: "Overland Park", russian: "Оверленд-Парк" },
  { state: "KS", english: "Kansas City", russian: "Канзас-Сити" },
  { state: "KS", english: "Olathe", russian: "Олат" },
  { state: "KS", english: "Topeka", russian: "Топика" },
  { state: "KS", english: "Lawrence", russian: "Лоуренс" },
  { state: "KS", english: "Shawnee", russian: "Шони" },
  { state: "KS", english: "Manhattan", russian: "Манхэттен" },
  { state: "KS", english: "Lenexa", russian: "Ленекса" },
  { state: "KS", english: "Salina", russian: "Салина" },

  // Kentucky
  { state: "KY", english: "Louisville", russian: "Луисвилл" },
  { state: "KY", english: "Lexington", russian: "Лексингтон" },
  { state: "KY", english: "Bowling Green", russian: "Боуллинг-Грин" },
  { state: "KY", english: "Owensboro", russian: "Оуэнсборо" },
  { state: "KY", english: "Covington", russian: "Ковингтон" },
  { state: "KY", english: "Hopkinsville", russian: "Хопкинсвилл" },
  { state: "KY", english: "Richmond", russian: "Ричмонд" },
  { state: "KY", english: "Florence", russian: "Флоренс" },
  { state: "KY", english: "Georgetown", russian: "Джорджтаун" },
  { state: "KY", english: "Henderson", russian: "Хендерсон" },

  // Louisiana
  { state: "LA", english: "New Orleans", russian: "Новый Орлеан" },
  { state: "LA", english: "Baton Rouge", russian: "Батон-Руж" },
  { state: "LA", english: "Shreveport", russian: "Шривпорт" },
  { state: "LA", english: "Lafayette", russian: "Лафайет" },
  { state: "LA", english: "Lake Charles", russian: "Лейк-Чарльз" },
  { state: "LA", english: "Kenner", russian: "Кеннер" },
  { state: "LA", english: "Bossier City", russian: "Боссьер-Сити" },
  { state: "LA", english: "Monroe", russian: "Монро" },
  { state: "LA", english: "Alexandria", russian: "Александрия" },
  { state: "LA", english: "Houma", russian: "Хума" },

  // Maine
  { state: "ME", english: "Portland", russian: "Портленд" },
  { state: "ME", english: "Lewiston", russian: "Льюистон" },
  { state: "ME", english: "Bangor", russian: "Бангор" },
  { state: "ME", english: "South Portland", russian: "Саут-Портленд" },
  { state: "ME", english: "Auburn", russian: "Оберн" },
  { state: "ME", english: "Biddeford", russian: "Биддефорд" },
  { state: "ME", english: "Sanford", russian: "Сэнфорд" },
  { state: "ME", english: "Saco", russian: "Сако" },
  { state: "ME", english: "Westbrook", russian: "Уэстбрук" },
  { state: "ME", english: "Augusta", russian: "Огаста" },

  // Maryland
  { state: "MD", english: "Baltimore", russian: "Балтимор" },
  { state: "MD", english: "Columbia", russian: "Колумбия" },
  { state: "MD", english: "Germantown", russian: "Германтаун" },
  { state: "MD", english: "Silver Spring", russian: "Силвер-Спринг" },
  { state: "MD", english: "Waldorf", russian: "Уолдорф" },
  { state: "MD", english: "Glen Burnie", russian: "Глен-Берни" },
  { state: "MD", english: "Frederick", russian: "Фредерик" },
  { state: "MD", english: "Gaithersburg", russian: "Гейтерсберг" },
  { state: "MD", english: "Rockville", russian: "Роквилл" },
  { state: "MD", english: "Bethesda", russian: "Бетесда" },

  // Massachusetts
  { state: "MA", english: "Boston", russian: "Бостон" },
  { state: "MA", english: "Worcester", russian: "Вустер" },
  { state: "MA", english: "Springfield", russian: "Спрингфилд" },
  { state: "MA", english: "Cambridge", russian: "Кембридж" },
  { state: "MA", english: "Lowell", russian: "Лоуэлл" },
  { state: "MA", english: "Brockton", russian: "Броктон" },
  { state: "MA", english: "New Bedford", russian: "Нью-Бедфорд" },
  { state: "MA", english: "Quincy", russian: "Куинси" },
  { state: "MA", english: "Lynn", russian: "Линн" },
  { state: "MA", english: "Fall River", russian: "Фолл-Ривер" },

  // Michigan
  { state: "MI", english: "Detroit", russian: "Детройт" },
  { state: "MI", english: "Grand Rapids", russian: "Гранд-Рапидс" },
  { state: "MI", english: "Warren", russian: "Уоррен" },
  { state: "MI", english: "Sterling Heights", russian: "Стерлинг-Хайтс" },
  { state: "MI", english: "Ann Arbor", russian: "Анн-Арбор" },
  { state: "MI", english: "Lansing", russian: "Лансинг" },
  { state: "MI", english: "Flint", russian: "Флинт" },
  { state: "MI", english: "Dearborn", russian: "Дирборн" },
  { state: "MI", english: "Livonia", russian: "Ливония" },
  { state: "MI", english: "Westland", russian: "Уэстленд" },

  // Minnesota
  { state: "MN", english: "Minneapolis", russian: "Миннеаполис" },
  { state: "MN", english: "St. Paul", russian: "Сент-Пол" },
  { state: "MN", english: "Rochester", russian: "Рочестер" },
  { state: "MN", english: "Duluth", russian: "Дулут" },
  { state: "MN", english: "Bloomington", russian: "Блумингтон" },
  { state: "MN", english: "Brooklyn Park", russian: "Бруклин-Парк" },
  { state: "MN", english: "Plymouth", russian: "Плимут" },
  { state: "MN", english: "Maple Grove", russian: "Мейпл-Гроув" },
  { state: "MN", english: "Woodbury", russian: "Вудбери" },
  { state: "MN", english: "Eagan", russian: "Иган" },

  // Mississippi
  { state: "MS", english: "Jackson", russian: "Джексон" },
  { state: "MS", english: "Gulfport", russian: "Галфпорт" },
  { state: "MS", english: "Southaven", russian: "Саутхейвен" },
  { state: "MS", english: "Biloxi", russian: "Билокси" },
  { state: "MS", english: "Hattiesburg", russian: "Хаттисберг" },
  { state: "MS", english: "Meridian", russian: "Меридиан" },
  { state: "MS", english: "Tupelo", russian: "Тупело" },
  { state: "MS", english: "Olive Branch", russian: "Олив Бранч" },
  { state: "MS", english: "Greenville", russian: "Гринвилл" },
  { state: "MS", english: "Horn Lake", russian: "Хорн Лейк" },

  // Missouri
  { state: "MO", english: "Kansas City", russian: "Канзас-Сити" },
  { state: "MO", english: "St. Louis", russian: "Сент-Луис" },
  { state: "MO", english: "Springfield", russian: "Спрингфилд" },
  { state: "MO", english: "Independence", russian: "Индепенденс" },
  { state: "MO", english: "Columbia", russian: "Колумбия" },
  { state: "MO", english: "Lee's Summit", russian: "Лис Саммит" },
  { state: "MO", english: "O'Fallon", russian: "О'Фаллон" },
  { state: "MO", english: "St. Joseph", russian: "Сент-Джозеф" },
  { state: "MO", english: "St. Charles", russian: "Сент-Чарльз" },
  { state: "MO", english: "St. Peters", russian: "Сент-Питерс" },

  // Montana
  { state: "MT", english: "Billings", russian: "Биллингс" },
  { state: "MT", english: "Missoula", russian: "Миссула" },
  { state: "MT", english: "Great Falls", russian: "Грейт-Фолс" },
  { state: "MT", english: "Bozeman", russian: "Бозмен" },
  { state: "MT", english: "Butte", russian: "Бьютт" },
  { state: "MT", english: "Helena", russian: "Хелена" },
  { state: "MT", english: "Kalispell", russian: "Калиспелл" },
  { state: "MT", english: "Havre", russian: "Хавр" },
  { state: "MT", english: "Anaconda", russian: "Анаконда" },
  { state: "MT", english: "Miles City", russian: "Майлс-Сити" },

  // Nebraska
  { state: "NE", english: "Omaha", russian: "Омаха" },
  { state: "NE", english: "Lincoln", russian: "Линкольн" },
  { state: "NE", english: "Bellevue", russian: "Белвью" },
  { state: "NE", english: "Grand Island", russian: "Гранд-Айленд" },
  { state: "NE", english: "Kearney", russian: "Карни" },
  { state: "NE", english: "Fremont", russian: "Фримонт" },
  { state: "NE", english: "Hastings", russian: "Хейстингс" },
  { state: "NE", english: "Norfolk", russian: "Норфолк" },
  { state: "NE", english: "North Platte", russian: "Норт-Платт" },
  { state: "NE", english: "Columbus", russian: "Колумбус" },

  // Nevada
  { state: "NV", english: "Las Vegas", russian: "Лас-Вегас" },
  { state: "NV", english: "Henderson", russian: "Хендерсон" },
  { state: "NV", english: "Reno", russian: "Рино" },
  { state: "NV", english: "North Las Vegas", russian: "Норт Лас-Вегас" },
  { state: "NV", english: "Sparks", russian: "Спаркс" },
  { state: "NV", english: "Carson City", russian: "Карсон-Сити" },
  { state: "NV", english: "Fernley", russian: "Фернли" },
  { state: "NV", english: "Elko", russian: "Элко" },
  { state: "NV", english: "Mesquite", russian: "Мескит" },
  { state: "NV", english: "Boulder City", russian: "Боулдер-Сити" },

  // New Hampshire
  { state: "NH", english: "Manchester", russian: "Манчестер" },
  { state: "NH", english: "Nashua", russian: "Нашуа" },
  { state: "NH", english: "Concord", russian: "Конкорд" },
  { state: "NH", english: "Derry", russian: "Дерри" },
  { state: "NH", english: "Dover", russian: "Довер" },
  { state: "NH", english: "Rochester", russian: "Рочестер" },
  { state: "NH", english: "Keene", russian: "Кин" },
  { state: "NH", english: "Portsmouth", russian: "Портсмут" },
  { state: "NH", english: "Laconia", russian: "Лакония" },
  { state: "NH", english: "Claremont", russian: "Клермонт" },

  // New Jersey
  { state: "NJ", english: "Newark", russian: "Ньюарк" },
  { state: "NJ", english: "Jersey City", russian: "Джерси-Сити" },
  { state: "NJ", english: "Paterson", russian: "Патерсон" },
  { state: "NJ", english: "Elizabeth", russian: "Элизабет" },
  { state: "NJ", english: "Lakewood", russian: "Лейквуд" },
  { state: "NJ", english: "Edison", russian: "Эдисон" },
  { state: "NJ", english: "Woodbridge", russian: "Вудбридж" },
  { state: "NJ", english: "Toms River", russian: "Томс Ривер" },
  { state: "NJ", english: "Hamilton", russian: "Гамильтон" },
  { state: "NJ", english: "Trenton", russian: "Трентон" },

  // New Mexico
  { state: "NM", english: "Albuquerque", russian: "Альбукерке" },
  { state: "NM", english: "Las Cruces", russian: "Лас-Крусес" },
  { state: "NM", english: "Santa Fe", russian: "Санта-Фе" },
  { state: "NM", english: "Rio Rancho", russian: "Рио-Ранчо" },
  { state: "NM", english: "Roswell", russian: "Розуэлл" },
  { state: "NM", english: "Farmington", russian: "Фармингтон" },
  { state: "NM", english: "Clovis", russian: "Кловис" },
  { state: "NM", english: "Hobbs", russian: "Хоббс" },
  { state: "NM", english: "Carlsbad", russian: "Карлсбад" },
  { state: "NM", english: "Gallup", russian: "Галлап" },

  // New York
  { state: "NY", english: "New York City", russian: "Нью-Йорк" },
  { state: "NY", english: "Buffalo", russian: "Баффало" },
  { state: "NY", english: "Rochester", russian: "Рочестер" },
  { state: "NY", english: "Yonkers", russian: "Йонкерс" },
  { state: "NY", english: "Syracuse", russian: "Сиракьюс" },
  { state: "NY", english: "Albany", russian: "Олбани" },
  { state: "NY", english: "New Rochelle", russian: "Нью-Рошелл" },
  { state: "NY", english: "Mount Vernon", russian: "Маунт-Вернон" },
  { state: "NY", english: "Schenectady", russian: "Скенектади" },
  { state: "NY", english: "Utica", russian: "Ютика" },

  // North Carolina
  { state: "NC", english: "Charlotte", russian: "Шарлотт" },
  { state: "NC", english: "Raleigh", russian: "Роли" },
  { state: "NC", english: "Greensboro", russian: "Гринсборо" },
  { state: "NC", english: "Durham", russian: "Дарем" },
  { state: "NC", english: "Winston-Salem", russian: "Уинстон-Сейлем" },
  { state: "NC", english: "Fayetteville", russian: "Фейетвилл" },
  { state: "NC", english: "Cary", russian: "Кэри" },
  { state: "NC", english: "Wilmington", russian: "Уилмингтон" },
  { state: "NC", english: "High Point", russian: "Хай-Пойнт" },
  { state: "NC", english: "Concord", russian: "Конкорд" },

  // North Dakota
  { state: "ND", english: "Fargo", russian: "Фарго" },
  { state: "ND", english: "Bismarck", russian: "Бисмарк" },
  { state: "ND", english: "Grand Forks", russian: "Гранд-Форкс" },
  { state: "ND", english: "Minot", russian: "Майнот" },
  { state: "ND", english: "West Fargo", russian: "Уэст-Фарго" },
  { state: "ND", english: "Williston", russian: "Уиллистон" },
  { state: "ND", english: "Dickinson", russian: "Дикинсон" },
  { state: "ND", english: "Mandan", russian: "Мандан" },
  { state: "ND", english: "Jamestown", russian: "Джемстаун" },
  { state: "ND", english: "Wahpeton", russian: "Вапетон" },

  // Ohio
  { state: "OH", english: "Columbus", russian: "Колумбус" },
  { state: "OH", english: "Cleveland", russian: "Кливленд" },
  { state: "OH", english: "Cincinnati", russian: "Цинциннати" },
  { state: "OH", english: "Toledo", russian: "Толидо" },
  { state: "OH", english: "Akron", russian: "Акрон" },
  { state: "OH", english: "Dayton", russian: "Дейтон" },
  { state: "OH", english: "Parma", russian: "Парма" },
  { state: "OH", english: "Canton", russian: "Кантон" },
  { state: "OH", english: "Youngstown", russian: "Янгстаун" },
  { state: "OH", english: "Lorain", russian: "Лорейн" },

  // Oklahoma
  { state: "OK", english: "Oklahoma City", russian: "Оклахома-Сити" },
  { state: "OK", english: "Tulsa", russian: "Талса" },
  { state: "OK", english: "Norman", russian: "Норман" },
  { state: "OK", english: "Broken Arrow", russian: "Брокен-Эрроу" },
  { state: "OK", english: "Edmond", russian: "Эдмонд" },
  { state: "OK", english: "Lawton", russian: "Лоутон" },
  { state: "OK", english: "Moore", russian: "Мур" },
  { state: "OK", english: "Midwest City", russian: "Мидвест-Сити" },
  { state: "OK", english: "Enid", russian: "Энид" },
  { state: "OK", english: "Stillwater", russian: "Стиллуотер" },

  // Oregon
  { state: "OR", english: "Portland", russian: "Портленд" },
  { state: "OR", english: "Salem", russian: "Сейлем" },
  { state: "OR", english: "Eugene", russian: "Юджин" },
  { state: "OR", english: "Gresham", russian: "Грешам" },
  { state: "OR", english: "Hillsboro", russian: "Хиллсборо" },
  { state: "OR", english: "Beaverton", russian: "Бивертон" },
  { state: "OR", english: "Bend", russian: "Бенд" },
  { state: "OR", english: "Medford", russian: "Медфорд" },
  { state: "OR", english: "Springfield", russian: "Спрингфилд" },
  { state: "OR", english: "Corvallis", russian: "Корваллис" },

  // Pennsylvania
  { state: "PA", english: "Philadelphia", russian: "Филадельфия" },
  { state: "PA", english: "Pittsburgh", russian: "Питтсбург" },
  { state: "PA", english: "Allentown", russian: "Аллентаун" },
  { state: "PA", english: "Erie", russian: "Эри" },
  { state: "PA", english: "Reading", russian: "Рединг" },
  { state: "PA", english: "Scranton", russian: "Скрантон" },
  { state: "PA", english: "Bethlehem", russian: "Бетлехем" },
  { state: "PA", english: "Lancaster", russian: "Ланкастер" },
  { state: "PA", english: "Harrisburg", russian: "Харрисберг" },
  { state: "PA", english: "York", russian: "Йорк" },

  // Rhode Island
  { state: "RI", english: "Providence", russian: "Провиденс" },
  { state: "RI", english: "Cranston", russian: "Кранстон" },
  { state: "RI", english: "Warwick", russian: "Уорик" },
  { state: "RI", english: "Pawtucket", russian: "Потакет" },
  { state: "RI", english: "East Providence", russian: "Ист-Провиденс" },
  { state: "RI", english: "Woonsocket", russian: "Вунсокет" },
  { state: "RI", english: "Newport", russian: "Ньюпорт" },
  { state: "RI", english: "Central Falls", russian: "Сентрал-Фолс" },
  { state: "RI", english: "Westerly", russian: "Уэстерли" },
  { state: "RI", english: "Valley Falls", russian: "Велли-Фолс" },

  // South Carolina
  { state: "SC", english: "Columbia", russian: "Колумбия" },
  { state: "SC", english: "Charleston", russian: "Чарлстон" },
  { state: "SC", english: "North Charleston", russian: "Норт Чарлстон" },
  { state: "SC", english: "Mount Pleasant", russian: "Маунт-Плезант" },
  { state: "SC", english: "Rock Hill", russian: "Рок-Хилл" },
  { state: "SC", english: "Greenville", russian: "Гринвилл" },
  { state: "SC", english: "Summerville", russian: "Саммервилл" },
  { state: "SC", english: "Goose Creek", russian: "Гус-Крик" },
  { state: "SC", english: "Sumter", russian: "Самтер" },
  { state: "SC", english: "Florence", russian: "Флоренс" },

  // South Dakota
  { state: "SD", english: "Sioux Falls", russian: "Су-Фолс" },
  { state: "SD", english: "Rapid City", russian: "Рапид-Сити" },
  { state: "SD", english: "Aberdeen", russian: "Абердин" },
  { state: "SD", english: "Brookings", russian: "Брукингс" },
  { state: "SD", english: "Watertown", russian: "Уотертаун" },
  { state: "SD", english: "Mitchell", russian: "Митчелл" },
  { state: "SD", english: "Yankton", russian: "Янктон" },
  { state: "SD", english: "Pierre", russian: "Пирр" },
  { state: "SD", english: "Huron", russian: "Хьюрон" },
  { state: "SD", english: "Spearfish", russian: "Сфирфиш" },

  // Tennessee
  { state: "TN", english: "Memphis", russian: "Мемфис" },
  { state: "TN", english: "Nashville", russian: "Нашвилл" },
  { state: "TN", english: "Knoxville", russian: "Ноксвилл" },
  { state: "TN", english: "Chattanooga", russian: "Чаттануга" },
  { state: "TN", english: "Clarksville", russian: "Кларксвилл" },
  { state: "TN", english: "Murfreesboro", russian: "Мерфрисборо" },
  { state: "TN", english: "Jackson", russian: "Джексон" },
  { state: "TN", english: "Johnson City", russian: "Джонсон-Сити" },
  { state: "TN", english: "Franklin", russian: "Франклин" },
  { state: "TN", english: "Bartlett", russian: "Бартлетт" },

  // Texas
  { state: "TX", english: "Houston", russian: "Хьюстон" },
  { state: "TX", english: "San Antonio", russian: "Сан-Антонио" },
  { state: "TX", english: "Dallas", russian: "Даллас" },
  { state: "TX", english: "Austin", russian: "Остин" },
  { state: "TX", english: "Fort Worth", russian: "Форт-Уэрт" },
  { state: "TX", english: "El Paso", russian: "Эль-Пасо" },
  { state: "TX", english: "Arlington", russian: "Арлингтон" },
  { state: "TX", english: "Corpus Christi", russian: "Корпус-Кристи" },
  { state: "TX", english: "Plano", russian: "Плейно" },
  { state: "TX", english: "Laredo", russian: "Ларедо" },

  // Utah
  { state: "UT", english: "Salt Lake City", russian: "Солт-Лейк-Сити" },
  { state: "UT", english: "West Valley City", russian: "Уэст-Вэлли-Сити" },
  { state: "UT", english: "Provo", russian: "Прово" },
  { state: "UT", english: "West Jordan", russian: "Уэст-Джордан" },
  { state: "UT", english: "Orem", russian: "Орем" },
  { state: "UT", english: "Sandy", russian: "Санди" },
  { state: "UT", english: "Ogden", russian: "Огден" },
  { state: "UT", english: "St. George", russian: "Сент-Джордж" },
  { state: "UT", english: "Layton", russian: "Лейтон" },
  { state: "UT", english: "South Jordan", russian: "Саут-Джордан" },

  // Vermont
  { state: "VT", english: "Burlington", russian: "Берлингтон" },
  { state: "VT", english: "South Burlington", russian: "Саут-Берлингтон" },
  { state: "VT", english: "Rutland", russian: "Ратленд" },
  { state: "VT", english: "Essex", russian: "Эссекс" },
  { state: "VT", english: "Colchester", russian: "Колчестер" },
  { state: "VT", english: "Bennington", russian: "Беннингтон" },
  { state: "VT", english: "Brattleboro", russian: "Браттлборо" },
  { state: "VT", english: "Milton", russian: "Милтон" },
  { state: "VT", english: "Hartford", russian: "Хартфорд" },
  { state: "VT", english: "Barre", russian: "Барре" },

  // Virginia
  { state: "VA", english: "Virginia Beach", russian: "Вирджиния-Бич" },
  { state: "VA", english: "Norfolk", russian: "Норфолк" },
  { state: "VA", english: "Chesapeake", russian: "Чесапик" },
  { state: "VA", english: "Richmond", russian: "Ричмонд" },
  { state: "VA", english: "Newport News", russian: "Ньюпорт Ньюс" },
  { state: "VA", english: "Alexandria", russian: "Александрия" },
  { state: "VA", english: "Hampton", russian: "Хэмптон" },
  { state: "VA", english: "Roanoke", russian: "Роанок" },
  { state: "VA", english: "Portsmouth", russian: "Портсмут" },
  { state: "VA", english: "Suffolk", russian: "Саффолк" },

  // Washington
  { state: "WA", english: "Seattle", russian: "Сиэтл" },
  { state: "WA", english: "Spokane", russian: "Спокан" },
  { state: "WA", english: "Tacoma", russian: "Такома" },
  { state: "WA", english: "Vancouver", russian: "Ванкувер" },
  { state: "WA", english: "Bellevue", russian: "Бельвью" },
  { state: "WA", english: "Kent", russian: "Кент" },
  { state: "WA", english: "Everett", russian: "Эверетт" },
  { state: "WA", english: "Renton", russian: "Рентон" },
  { state: "WA", english: "Federal Way", russian: "Федерал Уэй" },
  { state: "WA", english: "Yakima", russian: "Якима" },

  // West Virginia
  { state: "WV", english: "Charleston", russian: "Чарльстон" },
  { state: "WV", english: "Huntington", russian: "Хантингтон" },
  { state: "WV", english: "Parkersburg", russian: "Паркерсбург" },
  { state: "WV", english: "Morgantown", russian: "Моргантаун" },
  { state: "WV", english: "Wheeling", russian: "Уилинг" },
  { state: "WV", english: "Fairmont", russian: "Фэрмонт" },
  { state: "WV", english: "Martinsburg", russian: "Мартинсбург" },
  { state: "WV", english: "Beckley", russian: "Бекли" },
  { state: "WV", english: "Clarksburg", russian: "Кларксбург" },
  { state: "WV", english: "South Charleston", russian: "Саут Чарльстон" },


  // Wisconsin
  { state: "WI", english: "Milwaukee", russian: "Милуоки" },
  { state: "WI", english: "Madison", russian: "Мэдисон" },
  { state: "WI", english: "Green Bay", russian: "Грин-Бей" },
  { state: "WI", english: "Kenosha", russian: "Киноша" },
  { state: "WI", english: "Racine", russian: "Расин" },
  { state: "WI", english: "Appleton", russian: "Эпплтон" },
  { state: "WI", english: "Waukesha", russian: "Уокеша" },
  { state: "WI", english: "Oshkosh", russian: "Ошкош" },
  { state: "WI", english: "Eau Claire", russian: "О-Клэр" },
  { state: "WI", english: "Janesville", russian: "Джейнсвилл" },

  // Wyoming
  { state: "WY", english: "Cheyenne", russian: "Шайенн" },
  { state: "WY", english: "Casper", russian: "Каспер" },
  { state: "WY", english: "Laramie", russian: "Ларами" },
  { state: "WY", english: "Gillette", russian: "Джиллет" },
  { state: "WY", english: "Rock Springs", russian: "Рок-Спрингс" },
  { state: "WY", english: "Sheridan", russian: "Шеридан" },
  { state: "WY", english: "Green River", russian: "Грин-Ривер" },
  { state: "WY", english: "Evanston", russian: "Эванстон" },
  { state: "WY", english: "Riverton", russian: "Ривертон" },
  { state: "WY", english: "Jackson", russian: "Джексон" }
]